# win-setup:
# 	# choco 
# 	Set-ExecutionPolicy AllSigned
# 	Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# 	choco install Firefox Steam NordVPN 1Password RescueTime f.lux autohotkey Slack WhatsApp

# 	# swap command keys and invert scroll direction
# 	start macswaps.ahk

# 	Write-Host "Please import the inis from windows/wayneboard to setup the wayneboard"
# 	start macro-editor.exe
