#!/usr/bin/env node

const fs = require("fs");

fs.readdirSync("./").forEach(fileOrFolder => {
  const words = fileOrFolder
    .split(/[-_\s]+/)
    .map(string => string.toLowerCase());

  if (fs.lstatSync(fileOrFolder).isDirectory()) {
    const newPath = words
      .map(string =>
        string.charAt(0).toUpperCase() + string.slice(1))
      .join(" ");

    handleMove(fileOrFolder, newPath);
  } else {
    const newPath = words.join("-");

    handleMove(fileOrFolder, newPath);
  }
});

function handleMove(oldPath, newPath) {
  if (oldPath === newPath) {
    return;
  }

  let finalDestination = newPath;
  while (fs.existsSync(finalDestination)) {
    finalDestination = `${finalDestination}_copy`;
  }

  fs.renameSync(oldPath, finalDestination);
}
